### ISSUE TITLE
provide thumbnail example and link to page 

### ISSUE THREAD

**Issue by tacman** [wcmaart/collection#5]
The documentation says to get the thumbnail, use

https://get-thumb.herokuapp.com/getThumb.php?objectid=xxx

but objectid is never defined.  

I tried it with the id field and ULAN, but neither worked.

Also, can you provide a link back to the museum collection search page?  In the same way, I'm having a hard time trying to figure out how to use the data and provide a link back to the "official" page, e.g. https://egallery.williams.edu/objects/22166/

That is, where does the number in the URL come from?

Thanks.

**Comment by cweinard** [comment]
Hello, Thanks for your interest in the collection. You guessed correctly: the 'objectid' in the thumbnail url corresponds with the 'id' in the CSV and data. That number also corresponds with the number in the URL for the collection page.

The spoon...
https://egallery.williams.edu/objects/22166/
The spoon thumbnail...
https://get-thumb.herokuapp.com/getThumb.php?objectid=22166
(The service seems slow at the moment)

We'll need to make that clearer in the docs. Thanks

**Comment by tacman** [comment]
I see my problem, the first 2 lines of the CSV file go to

https://egallery.williams.edu/objects/1
https://egallery.williams.edu/objects/21

The IMAGE NOT AVAILABLE takes up the entire screen, so I didn't the data below it.  So it looked broken:

![image](https://user-images.githubusercontent.com/619585/229105736-f981f7c7-3b31-4589-ab31-5895a52a3675.png)
